name: pydysp
channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  # for jupyter notebooks
  - ipykernel
  # development dependencies
  - pytest
  - sphinx
  - sphinx-rtd-theme
  # pip dependencies
  - pip

  - pip:
      - -e .
      - tabulate
      # development dependencies
      - black
      - ruff
      - pre-commit
      # optional dependencies
      - sdypy-EMA